# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.28.8:3306/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
    show-sql: true
## 配置返回json格式字符串时,不返值为null的属性
  jackson:
    default-property-inclusion: non_null
# FREEMARKER配置
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      url_escaping_charset: UTF-8
      classic_compatible: true
      number_format: ###
## 服务访问路径
server:
  context-path: /sell
## 微信配置
wechat:
  mpAppId: wx6cd62266aa038924
  mpAppSecret: 9a711885bea1d12226313c82d18f3be2


