# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.4:3306/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
    show-sql: true
## 配置返回json格式字符串时,不返值为null的属性
  jackson:
    default-property-inclusion: non_null
# FREEMARKER配置
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      url_escaping_charset: UTF-8
      classic_compatible: true
      number_format: ###
# redis
  redis:
    host: 192.168.1.4
    port: 6379
    password:

## 服务访问路径
server:
  context-path: /sell
  port: 8080
## 微信配置
wechat:
  mpAppId: wx6cd62266aa038924
  mpAppSecret: 9a711885bea1d12226313c82d18f3be2
## 项目路径
projectUrl:
  sell: http://localhost:8080
## 设置日志输入级别
logging:
  level:
   com.liuqs.sell.dao.mapper: trace
## mybatis设置
mybatis:
  ## 设置别称
  type-aliases-package: com.liuqs.sell.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


