spring:
  #datasource配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiyu?characterEncoding=utf8
    username: root
    password: 123
    #druid数据库连接池配置
    druid:
      #初始化最大最小
      max-active: 20
      min-idle: 1
      initial-size: 1
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控系统统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  #jpa配置
  jpa:
    database: mysql
    #console打印sql
    show-sql: true



