spring:
  #datasource配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootstudy?characterEncoding=utf8
    username: root
    password: 123
  #jpa配置
  jpa:
    database: mysql
    #console打印sql
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


